/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RecuperarAccesoRouteImport } from "./routes/recuperar-acceso"
import { Route as PoliticaPrivacidadRouteImport } from "./routes/politica-privacidad"
import { Route as NosotrosRouteImport } from "./routes/nosotros"
import { Route as LoginAdminRouteImport } from "./routes/login-admin"
import { Route as CatalogoRouteImport } from "./routes/catalogo"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as ActualizarContrasenaRouteImport } from "./routes/actualizar-contrasena"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as ProyectoSlugRouteImport } from "./routes/proyecto/$slug"
import { Route as PropertiesIdRouteImport } from "./routes/properties/$id"
import { Route as AdminProyectosRouteImport } from "./routes/admin/proyectos"
import { Route as AdminPerfilRouteImport } from "./routes/admin/perfil"
import { Route as AdminLotesUnidadesRouteImport } from "./routes/admin/lotes-unidades"
import { Route as AdminGaleriasPlanosRecorridosRouteImport } from "./routes/admin/galerias-planos-recorridos"
import { Route as AdminEquipoAccesosRouteImport } from "./routes/admin/equipo-accesos"
import { Route as AdminConfiguracionRouteImport } from "./routes/admin/configuracion"
import { Route as AdminConfiguracionIndexRouteImport } from "./routes/admin/configuracion/index"
import { Route as AdminExperienciasVisorLotesRouteImport } from "./routes/admin/experiencias/visor-lotes"
import { Route as AdminExperienciasRecorridoTerrenoRouteImport } from "./routes/admin/experiencias/recorrido-terreno"
import { Route as AdminExperienciasMasterplanRouteImport } from "./routes/admin/experiencias/masterplan"
import { Route as AdminContenidoPortadaRouteImport } from "./routes/admin/contenido/portada"
import { Route as AdminContenidoSectionRouteImport } from "./routes/admin/contenido/$section"
import { Route as AdminConfiguracionNotificacionesRouteImport } from "./routes/admin/configuracion/notificaciones"
import { Route as AdminConfiguracionIntegracionesRouteImport } from "./routes/admin/configuracion/integraciones"
import { Route as AdminConfiguracionGeneralRouteImport } from "./routes/admin/configuracion/general"
import { Route as AdminConfiguracionDominiosRouteImport } from "./routes/admin/configuracion/dominios"
import { Route as AdminConfiguracionAparienciaRouteImport } from "./routes/admin/configuracion/apariencia"

const RecuperarAccesoRoute = RecuperarAccesoRouteImport.update({
  id: "/recuperar-acceso",
  path: "/recuperar-acceso",
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: "/politica-privacidad",
  path: "/politica-privacidad",
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: "/nosotros",
  path: "/nosotros",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: "/login-admin",
  path: "/login-admin",
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: "/catalogo",
  path: "/catalogo",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizarContrasenaRoute = ActualizarContrasenaRouteImport.update({
  id: "/actualizar-contrasena",
  path: "/actualizar-contrasena",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const ProyectoSlugRoute = ProyectoSlugRouteImport.update({
  id: "/proyecto/$slug",
  path: "/proyecto/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: "/properties/$id",
  path: "/properties/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProyectosRoute = AdminProyectosRouteImport.update({
  id: "/proyectos",
  path: "/proyectos",
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: "/perfil",
  path: "/perfil",
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesUnidadesRoute = AdminLotesUnidadesRouteImport.update({
  id: "/lotes-unidades",
  path: "/lotes-unidades",
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriasPlanosRecorridosRoute =
  AdminGaleriasPlanosRecorridosRouteImport.update({
    id: "/galerias-planos-recorridos",
    path: "/galerias-planos-recorridos",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEquipoAccesosRoute = AdminEquipoAccesosRouteImport.update({
  id: "/equipo-accesos",
  path: "/equipo-accesos",
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: "/configuracion",
  path: "/configuracion",
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminConfiguracionRoute,
} as any)
const AdminExperienciasVisorLotesRoute =
  AdminExperienciasVisorLotesRouteImport.update({
    id: "/experiencias/visor-lotes",
    path: "/experiencias/visor-lotes",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperienciasRecorridoTerrenoRoute =
  AdminExperienciasRecorridoTerrenoRouteImport.update({
    id: "/experiencias/recorrido-terreno",
    path: "/experiencias/recorrido-terreno",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperienciasMasterplanRoute =
  AdminExperienciasMasterplanRouteImport.update({
    id: "/experiencias/masterplan",
    path: "/experiencias/masterplan",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContenidoPortadaRoute = AdminContenidoPortadaRouteImport.update({
  id: "/contenido/portada",
  path: "/contenido/portada",
  getParentRoute: () => AdminRoute,
} as any)
const AdminContenidoSectionRoute = AdminContenidoSectionRouteImport.update({
  id: "/contenido/$section",
  path: "/contenido/$section",
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionNotificacionesRoute =
  AdminConfiguracionNotificacionesRouteImport.update({
    id: "/notificaciones",
    path: "/notificaciones",
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminConfiguracionIntegracionesRoute =
  AdminConfiguracionIntegracionesRouteImport.update({
    id: "/integraciones",
    path: "/integraciones",
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminConfiguracionGeneralRoute =
  AdminConfiguracionGeneralRouteImport.update({
    id: "/general",
    path: "/general",
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminConfiguracionDominiosRoute =
  AdminConfiguracionDominiosRouteImport.update({
    id: "/dominios",
    path: "/dominios",
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminConfiguracionAparienciaRoute =
  AdminConfiguracionAparienciaRouteImport.update({
    id: "/apariencia",
    path: "/apariencia",
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/actualizar-contrasena": typeof ActualizarContrasenaRoute
  "/admin": typeof AdminRouteWithChildren
  "/catalogo": typeof CatalogoRoute
  "/login-admin": typeof LoginAdminRoute
  "/nosotros": typeof NosotrosRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/recuperar-acceso": typeof RecuperarAccesoRoute
  "/admin/configuracion": typeof AdminConfiguracionRouteWithChildren
  "/admin/equipo-accesos": typeof AdminEquipoAccesosRoute
  "/admin/galerias-planos-recorridos": typeof AdminGaleriasPlanosRecorridosRoute
  "/admin/lotes-unidades": typeof AdminLotesUnidadesRoute
  "/admin/perfil": typeof AdminPerfilRoute
  "/admin/proyectos": typeof AdminProyectosRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/proyecto/$slug": typeof ProyectoSlugRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/configuracion/apariencia": typeof AdminConfiguracionAparienciaRoute
  "/admin/configuracion/dominios": typeof AdminConfiguracionDominiosRoute
  "/admin/configuracion/general": typeof AdminConfiguracionGeneralRoute
  "/admin/configuracion/integraciones": typeof AdminConfiguracionIntegracionesRoute
  "/admin/configuracion/notificaciones": typeof AdminConfiguracionNotificacionesRoute
  "/admin/contenido/$section": typeof AdminContenidoSectionRoute
  "/admin/contenido/portada": typeof AdminContenidoPortadaRoute
  "/admin/experiencias/masterplan": typeof AdminExperienciasMasterplanRoute
  "/admin/experiencias/recorrido-terreno": typeof AdminExperienciasRecorridoTerrenoRoute
  "/admin/experiencias/visor-lotes": typeof AdminExperienciasVisorLotesRoute
  "/admin/configuracion/": typeof AdminConfiguracionIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/actualizar-contrasena": typeof ActualizarContrasenaRoute
  "/catalogo": typeof CatalogoRoute
  "/login-admin": typeof LoginAdminRoute
  "/nosotros": typeof NosotrosRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/recuperar-acceso": typeof RecuperarAccesoRoute
  "/admin/equipo-accesos": typeof AdminEquipoAccesosRoute
  "/admin/galerias-planos-recorridos": typeof AdminGaleriasPlanosRecorridosRoute
  "/admin/lotes-unidades": typeof AdminLotesUnidadesRoute
  "/admin/perfil": typeof AdminPerfilRoute
  "/admin/proyectos": typeof AdminProyectosRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/proyecto/$slug": typeof ProyectoSlugRoute
  "/admin": typeof AdminIndexRoute
  "/admin/configuracion/apariencia": typeof AdminConfiguracionAparienciaRoute
  "/admin/configuracion/dominios": typeof AdminConfiguracionDominiosRoute
  "/admin/configuracion/general": typeof AdminConfiguracionGeneralRoute
  "/admin/configuracion/integraciones": typeof AdminConfiguracionIntegracionesRoute
  "/admin/configuracion/notificaciones": typeof AdminConfiguracionNotificacionesRoute
  "/admin/contenido/$section": typeof AdminContenidoSectionRoute
  "/admin/contenido/portada": typeof AdminContenidoPortadaRoute
  "/admin/experiencias/masterplan": typeof AdminExperienciasMasterplanRoute
  "/admin/experiencias/recorrido-terreno": typeof AdminExperienciasRecorridoTerrenoRoute
  "/admin/experiencias/visor-lotes": typeof AdminExperienciasVisorLotesRoute
  "/admin/configuracion": typeof AdminConfiguracionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/actualizar-contrasena": typeof ActualizarContrasenaRoute
  "/admin": typeof AdminRouteWithChildren
  "/catalogo": typeof CatalogoRoute
  "/login-admin": typeof LoginAdminRoute
  "/nosotros": typeof NosotrosRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/recuperar-acceso": typeof RecuperarAccesoRoute
  "/admin/configuracion": typeof AdminConfiguracionRouteWithChildren
  "/admin/equipo-accesos": typeof AdminEquipoAccesosRoute
  "/admin/galerias-planos-recorridos": typeof AdminGaleriasPlanosRecorridosRoute
  "/admin/lotes-unidades": typeof AdminLotesUnidadesRoute
  "/admin/perfil": typeof AdminPerfilRoute
  "/admin/proyectos": typeof AdminProyectosRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/proyecto/$slug": typeof ProyectoSlugRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/configuracion/apariencia": typeof AdminConfiguracionAparienciaRoute
  "/admin/configuracion/dominios": typeof AdminConfiguracionDominiosRoute
  "/admin/configuracion/general": typeof AdminConfiguracionGeneralRoute
  "/admin/configuracion/integraciones": typeof AdminConfiguracionIntegracionesRoute
  "/admin/configuracion/notificaciones": typeof AdminConfiguracionNotificacionesRoute
  "/admin/contenido/$section": typeof AdminContenidoSectionRoute
  "/admin/contenido/portada": typeof AdminContenidoPortadaRoute
  "/admin/experiencias/masterplan": typeof AdminExperienciasMasterplanRoute
  "/admin/experiencias/recorrido-terreno": typeof AdminExperienciasRecorridoTerrenoRoute
  "/admin/experiencias/visor-lotes": typeof AdminExperienciasVisorLotesRoute
  "/admin/configuracion/": typeof AdminConfiguracionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/actualizar-contrasena"
    | "/admin"
    | "/catalogo"
    | "/login-admin"
    | "/nosotros"
    | "/politica-privacidad"
    | "/recuperar-acceso"
    | "/admin/configuracion"
    | "/admin/equipo-accesos"
    | "/admin/galerias-planos-recorridos"
    | "/admin/lotes-unidades"
    | "/admin/perfil"
    | "/admin/proyectos"
    | "/properties/$id"
    | "/proyecto/$slug"
    | "/admin/"
    | "/admin/configuracion/apariencia"
    | "/admin/configuracion/dominios"
    | "/admin/configuracion/general"
    | "/admin/configuracion/integraciones"
    | "/admin/configuracion/notificaciones"
    | "/admin/contenido/$section"
    | "/admin/contenido/portada"
    | "/admin/experiencias/masterplan"
    | "/admin/experiencias/recorrido-terreno"
    | "/admin/experiencias/visor-lotes"
    | "/admin/configuracion/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/actualizar-contrasena"
    | "/catalogo"
    | "/login-admin"
    | "/nosotros"
    | "/politica-privacidad"
    | "/recuperar-acceso"
    | "/admin/equipo-accesos"
    | "/admin/galerias-planos-recorridos"
    | "/admin/lotes-unidades"
    | "/admin/perfil"
    | "/admin/proyectos"
    | "/properties/$id"
    | "/proyecto/$slug"
    | "/admin"
    | "/admin/configuracion/apariencia"
    | "/admin/configuracion/dominios"
    | "/admin/configuracion/general"
    | "/admin/configuracion/integraciones"
    | "/admin/configuracion/notificaciones"
    | "/admin/contenido/$section"
    | "/admin/contenido/portada"
    | "/admin/experiencias/masterplan"
    | "/admin/experiencias/recorrido-terreno"
    | "/admin/experiencias/visor-lotes"
    | "/admin/configuracion"
  id:
    | "__root__"
    | "/"
    | "/actualizar-contrasena"
    | "/admin"
    | "/catalogo"
    | "/login-admin"
    | "/nosotros"
    | "/politica-privacidad"
    | "/recuperar-acceso"
    | "/admin/configuracion"
    | "/admin/equipo-accesos"
    | "/admin/galerias-planos-recorridos"
    | "/admin/lotes-unidades"
    | "/admin/perfil"
    | "/admin/proyectos"
    | "/properties/$id"
    | "/proyecto/$slug"
    | "/admin/"
    | "/admin/configuracion/apariencia"
    | "/admin/configuracion/dominios"
    | "/admin/configuracion/general"
    | "/admin/configuracion/integraciones"
    | "/admin/configuracion/notificaciones"
    | "/admin/contenido/$section"
    | "/admin/contenido/portada"
    | "/admin/experiencias/masterplan"
    | "/admin/experiencias/recorrido-terreno"
    | "/admin/experiencias/visor-lotes"
    | "/admin/configuracion/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizarContrasenaRoute: typeof ActualizarContrasenaRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  LoginAdminRoute: typeof LoginAdminRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  RecuperarAccesoRoute: typeof RecuperarAccesoRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ProyectoSlugRoute: typeof ProyectoSlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/recuperar-acceso": {
      id: "/recuperar-acceso"
      path: "/recuperar-acceso"
      fullPath: "/recuperar-acceso"
      preLoaderRoute: typeof RecuperarAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/politica-privacidad": {
      id: "/politica-privacidad"
      path: "/politica-privacidad"
      fullPath: "/politica-privacidad"
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/nosotros": {
      id: "/nosotros"
      path: "/nosotros"
      fullPath: "/nosotros"
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login-admin": {
      id: "/login-admin"
      path: "/login-admin"
      fullPath: "/login-admin"
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/catalogo": {
      id: "/catalogo"
      path: "/catalogo"
      fullPath: "/catalogo"
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/actualizar-contrasena": {
      id: "/actualizar-contrasena"
      path: "/actualizar-contrasena"
      fullPath: "/actualizar-contrasena"
      preLoaderRoute: typeof ActualizarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/proyecto/$slug": {
      id: "/proyecto/$slug"
      path: "/proyecto/$slug"
      fullPath: "/proyecto/$slug"
      preLoaderRoute: typeof ProyectoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/properties/$id": {
      id: "/properties/$id"
      path: "/properties/$id"
      fullPath: "/properties/$id"
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/proyectos": {
      id: "/admin/proyectos"
      path: "/proyectos"
      fullPath: "/admin/proyectos"
      preLoaderRoute: typeof AdminProyectosRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/perfil": {
      id: "/admin/perfil"
      path: "/perfil"
      fullPath: "/admin/perfil"
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/lotes-unidades": {
      id: "/admin/lotes-unidades"
      path: "/lotes-unidades"
      fullPath: "/admin/lotes-unidades"
      preLoaderRoute: typeof AdminLotesUnidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/galerias-planos-recorridos": {
      id: "/admin/galerias-planos-recorridos"
      path: "/galerias-planos-recorridos"
      fullPath: "/admin/galerias-planos-recorridos"
      preLoaderRoute: typeof AdminGaleriasPlanosRecorridosRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/equipo-accesos": {
      id: "/admin/equipo-accesos"
      path: "/equipo-accesos"
      fullPath: "/admin/equipo-accesos"
      preLoaderRoute: typeof AdminEquipoAccesosRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/configuracion": {
      id: "/admin/configuracion"
      path: "/configuracion"
      fullPath: "/admin/configuracion"
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/configuracion/": {
      id: "/admin/configuracion/"
      path: "/"
      fullPath: "/admin/configuracion/"
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    "/admin/experiencias/visor-lotes": {
      id: "/admin/experiencias/visor-lotes"
      path: "/experiencias/visor-lotes"
      fullPath: "/admin/experiencias/visor-lotes"
      preLoaderRoute: typeof AdminExperienciasVisorLotesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/experiencias/recorrido-terreno": {
      id: "/admin/experiencias/recorrido-terreno"
      path: "/experiencias/recorrido-terreno"
      fullPath: "/admin/experiencias/recorrido-terreno"
      preLoaderRoute: typeof AdminExperienciasRecorridoTerrenoRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/experiencias/masterplan": {
      id: "/admin/experiencias/masterplan"
      path: "/experiencias/masterplan"
      fullPath: "/admin/experiencias/masterplan"
      preLoaderRoute: typeof AdminExperienciasMasterplanRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/contenido/portada": {
      id: "/admin/contenido/portada"
      path: "/contenido/portada"
      fullPath: "/admin/contenido/portada"
      preLoaderRoute: typeof AdminContenidoPortadaRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/contenido/$section": {
      id: "/admin/contenido/$section"
      path: "/contenido/$section"
      fullPath: "/admin/contenido/$section"
      preLoaderRoute: typeof AdminContenidoSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/configuracion/notificaciones": {
      id: "/admin/configuracion/notificaciones"
      path: "/notificaciones"
      fullPath: "/admin/configuracion/notificaciones"
      preLoaderRoute: typeof AdminConfiguracionNotificacionesRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    "/admin/configuracion/integraciones": {
      id: "/admin/configuracion/integraciones"
      path: "/integraciones"
      fullPath: "/admin/configuracion/integraciones"
      preLoaderRoute: typeof AdminConfiguracionIntegracionesRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    "/admin/configuracion/general": {
      id: "/admin/configuracion/general"
      path: "/general"
      fullPath: "/admin/configuracion/general"
      preLoaderRoute: typeof AdminConfiguracionGeneralRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    "/admin/configuracion/dominios": {
      id: "/admin/configuracion/dominios"
      path: "/dominios"
      fullPath: "/admin/configuracion/dominios"
      preLoaderRoute: typeof AdminConfiguracionDominiosRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    "/admin/configuracion/apariencia": {
      id: "/admin/configuracion/apariencia"
      path: "/apariencia"
      fullPath: "/admin/configuracion/apariencia"
      preLoaderRoute: typeof AdminConfiguracionAparienciaRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
  }
}

interface AdminConfiguracionRouteChildren {
  AdminConfiguracionAparienciaRoute: typeof AdminConfiguracionAparienciaRoute
  AdminConfiguracionDominiosRoute: typeof AdminConfiguracionDominiosRoute
  AdminConfiguracionGeneralRoute: typeof AdminConfiguracionGeneralRoute
  AdminConfiguracionIntegracionesRoute: typeof AdminConfiguracionIntegracionesRoute
  AdminConfiguracionNotificacionesRoute: typeof AdminConfiguracionNotificacionesRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
}

const AdminConfiguracionRouteChildren: AdminConfiguracionRouteChildren = {
  AdminConfiguracionAparienciaRoute: AdminConfiguracionAparienciaRoute,
  AdminConfiguracionDominiosRoute: AdminConfiguracionDominiosRoute,
  AdminConfiguracionGeneralRoute: AdminConfiguracionGeneralRoute,
  AdminConfiguracionIntegracionesRoute: AdminConfiguracionIntegracionesRoute,
  AdminConfiguracionNotificacionesRoute: AdminConfiguracionNotificacionesRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
}

const AdminConfiguracionRouteWithChildren =
  AdminConfiguracionRoute._addFileChildren(AdminConfiguracionRouteChildren)

interface AdminRouteChildren {
  AdminConfiguracionRoute: typeof AdminConfiguracionRouteWithChildren
  AdminEquipoAccesosRoute: typeof AdminEquipoAccesosRoute
  AdminGaleriasPlanosRecorridosRoute: typeof AdminGaleriasPlanosRecorridosRoute
  AdminLotesUnidadesRoute: typeof AdminLotesUnidadesRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProyectosRoute: typeof AdminProyectosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContenidoSectionRoute: typeof AdminContenidoSectionRoute
  AdminContenidoPortadaRoute: typeof AdminContenidoPortadaRoute
  AdminExperienciasMasterplanRoute: typeof AdminExperienciasMasterplanRoute
  AdminExperienciasRecorridoTerrenoRoute: typeof AdminExperienciasRecorridoTerrenoRoute
  AdminExperienciasVisorLotesRoute: typeof AdminExperienciasVisorLotesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracionRoute: AdminConfiguracionRouteWithChildren,
  AdminEquipoAccesosRoute: AdminEquipoAccesosRoute,
  AdminGaleriasPlanosRecorridosRoute: AdminGaleriasPlanosRecorridosRoute,
  AdminLotesUnidadesRoute: AdminLotesUnidadesRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProyectosRoute: AdminProyectosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContenidoSectionRoute: AdminContenidoSectionRoute,
  AdminContenidoPortadaRoute: AdminContenidoPortadaRoute,
  AdminExperienciasMasterplanRoute: AdminExperienciasMasterplanRoute,
  AdminExperienciasRecorridoTerrenoRoute:
    AdminExperienciasRecorridoTerrenoRoute,
  AdminExperienciasVisorLotesRoute: AdminExperienciasVisorLotesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizarContrasenaRoute: ActualizarContrasenaRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  LoginAdminRoute: LoginAdminRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  RecuperarAccesoRoute: RecuperarAccesoRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ProyectoSlugRoute: ProyectoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
