/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PoliticaPrivacidadRouteImport } from "./routes/politica-privacidad"
import { Route as CatalogoRouteImport } from "./routes/catalogo"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PropertiesIdRouteImport } from "./routes/properties/$id"

const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: "/politica-privacidad",
  path: "/politica-privacidad",
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: "/catalogo",
  path: "/catalogo",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: "/properties/$id",
  path: "/properties/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/catalogo": typeof CatalogoRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/properties/$id": typeof PropertiesIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/catalogo": typeof CatalogoRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/properties/$id": typeof PropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/catalogo": typeof CatalogoRoute
  "/politica-privacidad": typeof PoliticaPrivacidadRoute
  "/properties/$id": typeof PropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/catalogo" | "/politica-privacidad" | "/properties/$id"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/catalogo" | "/politica-privacidad" | "/properties/$id"
  id:
    "__root__" | "/" | "/catalogo" | "/politica-privacidad" | "/properties/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/politica-privacidad": {
      id: "/politica-privacidad"
      path: "/politica-privacidad"
      fullPath: "/politica-privacidad"
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/catalogo": {
      id: "/catalogo"
      path: "/catalogo"
      fullPath: "/catalogo"
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/properties/$id": {
      id: "/properties/$id"
      path: "/properties/$id"
      fullPath: "/properties/$id"
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  PropertiesIdRoute: PropertiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
